name: Update Sanctions List

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:      # Allows manual trigger

jobs:
  update-sanctions:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install axios cheerio

    - name: Run update script
      run: node scripts/update-sanctions.js

    - name: Commit if changes exist
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add data/sanctioned-addresses.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update sanctions list $(date +'%Y-%m-%d')" && git push)